# Generated by Django 5.2.15 on 2026-06-12 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('holiday_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/banners/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaigns/covers/')),
                ('draw_date', models.DateTimeField()),
                ('registration_start_date', models.DateTimeField()),
                ('registration_end_date', models.DateTimeField()),
                ('telegram_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed'), ('Drawn', 'Drawn')], default='Draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
