# Generated by Django 5.2.15 on 2026-06-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draws', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='registrations.registration'),
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('campaign', 'registration')},
        ),
    ]
