# Generated by Django 5.2.15 on 2026-06-12 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('lottery_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='campaigns.campaign')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='campaigns.department')),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='payments.paymentplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'phone_number')},
            },
        ),
    ]
