# Generated by Django 5.2.15 on 2026-06-12 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='registrations.registration'),
        ),
        migrations.AddField(
            model_name='installmentrequest',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='payments.installment'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='installment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='payments.installment'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('registration', 'installment_number')},
        ),
    ]
